--- 
javascripts: 
- app: 
  - jquery
  - jquery.sifr.min
  - jquery.media
  - 1jquery.flash
  - jquery.dwFadingLinks
  - superfish
  - ufo
  - jquery.delay
  - jquery.tableDnD
  - jquery.simplemodal
  - application
- promo:
  - jquery
  - jquery.delay
  - jquery.jcarousellite
  - ufo
  - promotional
stylesheets:
- app:
  - base
  - layout
  - common
  - superfish-vertical
  - basic
- promo:
  - layout
  - promotional
  - forms
  - flash
  - promotional_theme

